  unsigned int events[] = {
    PEVT_UNDEF,                                //0
    PEVT_AXU_INSTR_COMMIT,                     //1
    PEVT_AXU_CR_COMMIT,                        //2
    PEVT_AXU_IDLE,                             //3
    PEVT_AXU_FP_DS_ACTIVE,                     //4
    PEVT_AXU_FP_DS_ACTIVE_CYC,                 //5
    PEVT_AXU_DENORM_FLUSH,                     //6
    PEVT_AXU_UCODE_OPS_COMMIT,                 //7
    PEVT_AXU_FP_EXCEPT,                        //8
    PEVT_AXU_FP_ENAB_EXCEPT,                   //9
    PEVT_IU_IL1_MISS,                          //10
    PEVT_IU_IL1_MISS_CYC,                      //11
    PEVT_IU_IL1_RELOADS_DROPPED,               //12
    PEVT_IU_RELOAD_COLLISIONS,                 //13
    PEVT_IU_RELOAD_COLLISIONS_CYC,             //14
    PEVT_IU_IU0_REDIR_CYC,                     //15
    PEVT_IU_IERAT_MISS,                        //16
    PEVT_IU_IERAT_MISS_CYC,                    //17
    PEVT_IU_ICACHE_FETCH,                      //18
    PEVT_IU_ICACHE_FETCH_CYC,                  //19
    PEVT_IU_INSTR_FETCHED,                     //20
    PEVT_IU_INSTR_FETCHED_CYC,                 //21
    PEVT_IU_RSV_ANY_L2_BACK_INV,               //22
    PEVT_IU_RSV_ANY_L2_BACK_INV_CYC,           //23
    PEVT_IU_L2_BACK_INV_HITS,                  //24
    PEVT_IU_L2_BACK_INV_HITS_CYC,              //25
    PEVT_IU_IBUFF_EMPTY,                       //26
    PEVT_IU_IBUFF_EMPTY_CYC,                   //27
    PEVT_IU_IBUFF_FLUSH,                       //28
    PEVT_IU_IBUFF_FLUSH_CYC,                   //29
    PEVT_IU_IS1_STALL_CYC,                     //30
    PEVT_IU_IS2_STALL_CYC,                     //31
    PEVT_IU_BARRIER_OP_STALL_CYC,              //32
    PEVT_IU_SLOW_SPR_ACCESS_CYC,               //33
    PEVT_IU_RAW_DEP_HIT_CYC,                   //34
    PEVT_IU_WAW_DEP_HIT_CYC,                   //35
    PEVT_IU_SYNC_DEP_HIT_CYC,                  //36
    PEVT_IU_SPR_DEP_HIT_CYC,                   //37
    PEVT_IU_AXU_DEP_HIT_CYC,                   //38
    PEVT_IU_FXU_DEP_HIT_CYC,                   //39
    PEVT_IU_AXU_FXU_DEP_HIT_CYC,               //40
    PEVT_IU_AXU_ISSUE_PRI_LOSS_CYC,            //41
    PEVT_IU_FXU_ISSUE_PRI_LOSS_CYC,            //42
    PEVT_IU_FXU_ISSUE_COUNT,                   //43
    PEVT_IU_TOT_ISSUE_COUNT,                   //44
    PEVT_XU_PROC_BUSY,                         //45
    PEVT_XU_BR_COMMIT_CORE,                    //46
    PEVT_XU_BR_MISPRED_COMMIT_CORE,            //47
    PEVT_XU_BR_TARG_ADDR_MISPRED_COMMIT_CORE,  //48
    PEVT_XU_THRD_RUNNING,                      //49
    PEVT_XU_TIMEBASE_TICK,                     //50
    PEVT_XU_SPR_READ_COMMIT,                   //51
    PEVT_XU_SPR_WRITE_COMMIT,                  //52
    PEVT_XU_STALLED_ON_WAITRSV,                //53
    PEVT_XU_STALLED_ON_WAITRSV_CYC,            //54
    PEVT_XU_EXT_INT_ASSERT,                    //55
    PEVT_XU_CRIT_EXT_INT_ASSERT,               //56
    PEVT_XU_PERF_MON_INT_ASSERT,               //57
    PEVT_XU_PPC_COMMIT,                        //58
    PEVT_XU_COMMIT,                            //59
    PEVT_XU_UCODE_COMMIT,                      //60
    PEVT_XU_ANY_FLUSH,                         //61
    PEVT_XU_BR_COMMIT,                         //62
    PEVT_XU_BR_MISPRED_COMMIT,                 //63
    PEVT_XU_BR_TAKEN_COMMIT,                   //64
    PEVT_XU_BR_TARG_ADDR_MISPRED_COMMIT,       //65
    PEVT_XU_MULT_DIV_COLLISION,                //66
    PEVT_XU_EXT_INT_PEND,                      //67
    PEVT_XU_CRIT_EXT_INT_PEND,                 //68
    PEVT_XU_PERF_MON_INT_PEND,                 //69
    PEVT_XU_RUN_INSTR,                         //70
    PEVT_XU_INTS_TAKEN,                        //71
    PEVT_XU_EXT_INT_TAKEN,                     //72
    PEVT_XU_CRIT_EXT_INT_TAKEN,                //73
    PEVT_XU_PERF_MON_INT_TAKEN,                //74
    PEVT_XU_DOORBELL_INT_TAKEN,                //75
    PEVT_XU_STCX_FAIL,                         //76
    PEVT_XU_ICSWX_FAILED,                      //77
    PEVT_XU_ICSWX_COMMIT,                      //78
    PEVT_XU_MULT_DIV_BUSY,                     //79
    PEVT_LSU_COMMIT_STS,                       //80
    PEVT_LSU_COMMIT_ST_MISSES,                 //81
    PEVT_LSU_COMMIT_LD_MISSES,                 //82
    PEVT_LSU_COMMIT_CACHE_INHIB_LD_MISSES,     //83
    PEVT_LSU_COMMIT_CACHEABLE_LDS,             //84
    PEVT_LSU_COMMIT_DCBT_MISSES,               //85
    PEVT_LSU_COMMIT_DCBT_HITS,                 //86
    PEVT_LSU_COMMIT_AXU_LDS,                   //87
    PEVT_LSU_COMMIT_AXU_STS,                   //88
    PEVT_LSU_COMMIT_STCX,                      //89
    PEVT_LSU_COMMIT_WCLR,                      //90
    PEVT_LSU_COMMIT_WCLR_WL,                   //91
    PEVT_LSU_COMMIT_LDAWX,                     //92
    PEVT_LSU_UNSUPPORTED_ALIGNMENT_FLUSH,      //93
    PEVT_LSU_RELOAD_RESRC_CONFLICT_FLUSH,      //94
    PEVT_LSU_COMMIT_DUPLICATE_LDAWX,           //95
    PEVT_LSU_INTER_THRD_DIR_ACCESS_FLUSH,      //96
    PEVT_LSU_LMQ_DEPENDENCY_FLUSH,             //97
    PEVT_LSU_COMMIT_WCHKALL,                   //98
    PEVT_LSU_COMMIT_SUCC_WCHKALL,              //99
    PEVT_LSU_LD_MISS_Q_FULL_FLUSH,             //100
    PEVT_LSU_ST_Q_FULL_FLUSH,                  //101
    PEVT_LSU_HIT_LD_FLUSH,                     //102
    PEVT_LSU_HIT_IG1_REQ_FLUSH,                //103
    PEVT_LSU_LARX_FINISHED,                    //104
    PEVT_LSU_INTER_THRD_ST_WATCH_LOST,         //105
    PEVT_LSU_RELOAD_WATCH_LOST,                //106
    PEVT_LSU_BACK_INV_WATCH_LOST,              //107
    PEVT_LSU_L1_DCACHE_BACK_INVAL,             //108
    PEVT_LSU_L1_DCACHE_BACK_INVAL_HITS,        //109
    PEVT_LSU_L1_CACHE_PTYERR_DETECTED,         //110
    PEVT_LSU_LD_LAT_MEM_SUBSYS_CYC,            //111
    PEVT_MMU_TLB_HIT_DIRECT_IERAT,             //112
    PEVT_MMU_TLB_MISS_DIRECT_IERAT,            //113
    PEVT_MMU_TLB_MISS_INDIR_IERAT,             //114
    PEVT_MMU_HTW_HIT_IERAT,                    //115
    PEVT_MMU_HTW_MISS_IERAT,                   //116
    PEVT_MMU_TLB_HIT_DIRECT_DERAT,             //117
    PEVT_MMU_TLB_MISS_DIRECT_DERAT,            //118
    PEVT_MMU_TLB_MISS_INDIR_DERAT,             //119
    PEVT_MMU_HTW_HIT_DERAT,                    //120
    PEVT_MMU_HTW_MISS_DERAT,                   //121
    PEVT_MMU_IERAT_MISS,                       //122
    PEVT_MMU_IERAT_MISS_CYC,                   //123
    PEVT_MMU_DERAT_MISS,                       //124
    PEVT_MMU_DERAT_MISS_CYC,                   //125
    PEVT_MMU_IERAT_MISS_TOT,                   //126
    PEVT_MMU_DERAT_MISS_TOT,                   //127
    PEVT_MMU_TLB_MISS_DIRECT_TOT,              //128
    PEVT_MMU_TLB_HIT_FIRSTSIZE_TOT,            //129
    PEVT_MMU_TLB_HIT_INDIR_TOT,                //130
    PEVT_MMU_HTW_PTERELOAD_TOT,                //131
    PEVT_MMU_LRAT_TRANS_TOT,                   //132
    PEVT_MMU_LRAT_MISS_TOT,                    //133
    PEVT_MMU_PT_FAULT_TOT,                     //134
    PEVT_MMU_PT_INELIG_TOT,                    //135
    PEVT_MMU_TLBWEC_FAIL_TOT,                  //136
    PEVT_MMU_TLBWEC_SUCC_TOT,                  //137
    PEVT_MMU_TLBILX_SRC_TOT,                   //138
    PEVT_MMU_TLBIVAX_SRC_TOT,                  //139
    PEVT_MMU_TLBIVAX_SNOOP_TOT,                //140
    PEVT_MMU_TLB_FLUSH_REQ_TOT,                //141
    PEVT_MMU_TLB_FLUSH_REQ_TOT_CYC,            //142
    PEVT_L1P_BAS_STRM_LINE_ESTB,               //143
    PEVT_L1P_BAS_HIT,                          //144
    PEVT_L1P_BAS_PF2DFC,                       //145
    PEVT_L1P_BAS_MISS,                         //146
    PEVT_L1P_BAS_LU_DRAIN,                     //147
    PEVT_L1P_BAS_LU_DRAIN_CYC,                 //148
    PEVT_L1P_BAS_LD,                           //149
    PEVT_L1P_BAS_ST_WC,                        //150
    PEVT_L1P_BAS_ST_32BYTE,                    //151
    PEVT_L1P_BAS_ST_CRACKED,                   //152
    PEVT_L1P_BAS_LU_STALL_SRT,                 //153
    PEVT_L1P_BAS_LU_STALL_SRT_CYC,             //154
    PEVT_L1P_BAS_LU_STALL_MMIO_DCR,            //155
    PEVT_L1P_BAS_LU_STALL_MMIO_DCR_CYC,        //156
    PEVT_L1P_BAS_LU_STALL_STRM_DET,            //157
    PEVT_L1P_BAS_LU_STALL_STRM_DET_CYC,        //158
    PEVT_L1P_BAS_LU_STALL_LIST_RD,             //159
    PEVT_L1P_BAS_LU_STALL_LIST_RD_CYC,         //160
    PEVT_L1P_BAS_ST,                           //161
    PEVT_L1P_BAS_LU_STALL_LIST_WRT,            //162
    PEVT_L1P_BAS_LU_STALL_LIST_WRT_CYC,        //163
    PEVT_L1P_SW_MAS_SW_REQ_VAL,                //164
    PEVT_L1P_SW_MAS_SW_REQ_GATE,               //165
    PEVT_L1P_SW_MAS_SW_DATA_GATE,              //166
    PEVT_L1P_SW_SR_MAS_RD_VAL_2,               //167
    PEVT_L1P_SW_SI_MAS_REQ_VAL_2,              //168
    PEVT_L1P_SW_SW_MAS_SKED_VAL_2,             //169
    PEVT_L1P_SW_SW_MAS_EAGER_VAL_2,            //170
    PEVT_L1P_SW_TLB_FILL,                      //171
    PEVT_L1P_SW_STWCX_FAIL,                    //172
    PEVT_L1P_SW_STWCX,                         //173
    PEVT_L1P_SW_I_FETCH,                       //174
    PEVT_L1P_SW_MSYNC,                         //175
    PEVT_L1P_SW_LWARX,                         //176
    PEVT_L1P_SW_KILL_L2_RSV,                   //177
    PEVT_L1P_SW_L2_CANCEL_A2_RSV,              //178
    PEVT_L1P_SW_L1_INVAL,                      //179
    PEVT_L1P_SW_WC_EVICT_ADDR,                 //180
    PEVT_L1P_STRM_LINE_ESTB,                   //181
    PEVT_L1P_STRM_HIT_FWD,                     //182
    PEVT_L1P_STRM_L1_HIT_FWD,                  //183
    PEVT_L1P_STRM_EVICT_UNUSED,                //184
    PEVT_L1P_STRM_EVICT_PART_USED,             //185
    PEVT_L1P_STRM_REMOTE_INVAL_MATCH,          //186
    PEVT_L1P_STRM_DONT_CACHE,                  //187
    PEVT_L1P_STRM_STRM_DEPTH_STEAL,            //188
    PEVT_L1P_STRM_STRM_ESTB,                   //189
    PEVT_L1P_STRM_WRT_INVAL,                   //190
    PEVT_L1P_STRM_LINE_ESTB_ALL_LIST,          //191
    PEVT_L1P_STRM_HIT_LIST,                    //192
    PEVT_L1P_STRM_PF2DFC_LIST,                 //193
    PEVT_L1P_STRM_PART_INVAL_REFCH,            //194
    PEVT_L1P_LIST_SKIP_1,                      //195
    PEVT_L1P_LIST_SKIP_2,                      //196
    PEVT_L1P_LIST_SKIP_3,                      //197
    PEVT_L1P_LIST_SKIP_4,                      //198
    PEVT_L1P_LIST_SKIP_5,                      //199
    PEVT_L1P_LIST_SKIP_6,                      //200
    PEVT_L1P_LIST_SKIP_7,                      //201
    PEVT_L1P_LIST_ABANDON,                     //202
    PEVT_L1P_LIST_CMP,                         //203
    PEVT_L1P_LIST_SKIP,                        //204
    PEVT_L1P_LIST_MISMATCH,                    //205
    PEVT_L1P_LIST_STARTED,                     //206
    PEVT_L1P_LIST_OVF_MEM,                     //207
    PEVT_L1P_LIST_CMP_OVRUN_PREFCH,            //208
    PEVT_WAKE_HIT_10,                          //209
    PEVT_WAKE_HIT_11,                          //210
    PEVT_CYCLES,                               //211
    PEVT_INST_XU_MATCH,                        //212
    PEVT_INST_XU_GRP_MASK,                     //213
    PEVT_INST_XU_FLD,                          //214
    PEVT_INST_XU_FST,                          //215
    PEVT_INST_XU_QLD,                          //216
    PEVT_INST_XU_QST,                          //217
    PEVT_INST_XU_BITS,                         //218
    PEVT_INST_XU_BRC,                          //219
    PEVT_INST_XU_BRU,                          //220
    PEVT_INST_XU_CINV,                         //221
    PEVT_INST_XU_CSTO,                         //222
    PEVT_INST_XU_CTCH,                         //223
    PEVT_INST_XU_IADD,                         //224
    PEVT_INST_XU_ICMP,                         //225
    PEVT_INST_XU_ICSW,                         //226
    PEVT_INST_XU_IDIV,                         //227
    PEVT_INST_XU_ILOG,                         //228
    PEVT_INST_XU_IMOV,                         //229
    PEVT_INST_XU_IMUL,                         //230
    PEVT_INST_XU_INT,                          //231
    PEVT_INST_XU_LD,                           //232
    PEVT_INST_XU_LSCX,                         //233
    PEVT_INST_XU_ST,                           //234
    PEVT_INST_XU_SYNC,                         //235
    PEVT_INST_XU_TLB,                          //236
    PEVT_INST_XU_TLBI,                         //237
    PEVT_INST_XU_WCH,                          //238
    PEVT_INST_XU_ALL,                          //239
    PEVT_INST_QFPU_MATCH,                      //240
    PEVT_INST_QFPU_GRP_MASK,                   //241
    PEVT_INST_QFPU_FOTH,                       //242
    PEVT_INST_QFPU_FRES,                       //243
    PEVT_INST_QFPU_FADD,                       //244
    PEVT_INST_QFPU_FCVT,                       //245
    PEVT_INST_QFPU_FCMP,                       //246
    PEVT_INST_QFPU_FDIV,                       //247
    PEVT_INST_QFPU_FMOV,                       //248
    PEVT_INST_QFPU_FMA,                        //249
    PEVT_INST_QFPU_FMUL,                       //250
    PEVT_INST_QFPU_FRND,                       //251
    PEVT_INST_QFPU_FSQE,                       //252
    PEVT_INST_QFPU_FSQ,                        //253
    PEVT_INST_QFPU_QMOV,                       //254
    PEVT_INST_QFPU_QOTH,                       //255
    PEVT_INST_QFPU_QADD,                       //256
    PEVT_INST_QFPU_QMUL,                       //257
    PEVT_INST_QFPU_QRES,                       //258
    PEVT_INST_QFPU_QMA,                        //259
    PEVT_INST_QFPU_QRND,                       //260
    PEVT_INST_QFPU_QCVT,                       //261
    PEVT_INST_QFPU_QCMP,                       //262
    PEVT_INST_QFPU_UCODE,                      //263
    PEVT_INST_QFPU_ALL,                        //264
    PEVT_INST_QFPU_FPGRP1,                     //265
    PEVT_INST_QFPU_FPGRP1_SINGLE,              //266
    PEVT_INST_QFPU_FPGRP1_QUAD,                //267
    PEVT_INST_QFPU_FPGRP2,                     //268
    PEVT_INST_QFPU_FPGRP2_SINGLE,              //269
    PEVT_INST_QFPU_FPGRP2_QUAD,                //270
    PEVT_INST_QFPU_FPGRP1_INSTR,               //271
    PEVT_INST_QFPU_FPGRP1_SINGLE_INSTR,        //272
    PEVT_INST_QFPU_FPGRP1_QUAD_INSTR,          //273
    PEVT_INST_QFPU_FPGRP2_INSTR,               //274
    PEVT_INST_QFPU_FPGRP2_SINGLE_INSTR,        //275
    PEVT_INST_QFPU_FPGRP2_QUAD_INSTR,          //276
    PEVT_INST_ALL,                             //277
    PEVT_L2_HITS,                              //278
    PEVT_L2_MISSES,                            //279
    PEVT_L2_PREFETCH,                          //280
    PEVT_L2_FETCH_LINE,                        //281
    PEVT_L2_STORE_LINE,                        //282
    PEVT_L2_STORE_PARTIAL_LINE,                //283
    PEVT_L2_REQ_REJECT,                        //284
    PEVT_L2_REQ_RETIRE,                        //285
    PEVT_L2_REQ_MISS_AND_EVICT,                //286
    PEVT_L2_REQ_MISS_AND_EVICT_SPEC,           //287
    PEVT_L2_MISS_AND_EVICT,                    //288
    PEVT_L2_MISS_AND_EVICT_SPEC,               //289
    PEVT_L2_REQ_SPEC_ADDR_CLEANUP,             //290
    PEVT_L2_SPEC_ADDR_CLEANUP,                 //291
    PEVT_L2_SPEC_SET_CLEANUP,                  //292
    PEVT_L2_SPEC_RETRY,                        //293
    PEVT_L2_HITS_SLICE,                        //294
    PEVT_L2_MISSES_SLICE,                      //295
    PEVT_L2_PREFETCH_SLICE,                    //296
    PEVT_L2_FETCH_LINE_SLICE,                  //297
    PEVT_L2_STORE_LINE_SLICE,                  //298
    PEVT_L2_STORE_PARTIAL_LINE_SLICE,          //299
    PEVT_L2_REQ_REJECT_SLICE,                  //300
    PEVT_L2_REQ_RETIRE_SLICE,                  //301
    PEVT_L2_REQ_MISS_AND_EVICT_SLICE,          //302
    PEVT_L2_REQ_MISS_AND_EVICT_SPEC_SLICE,     //303
    PEVT_L2_MISS_AND_EVICT_SLICE,              //304
    PEVT_L2_MISS_AND_EVICT_SPEC_SLICE,         //305
    PEVT_L2_REQ_SPEC_ADDR_CLEANUP_SLICE,       //306
    PEVT_L2_SPEC_ADDR_CLEANUP_SLICE,           //307
    PEVT_L2_SPEC_SET_CLEANUP_SLICE,            //308
    PEVT_L2_SPEC_RETRY_SLICE,                  //309
    PEVT_MU_PKT_INJ,                           //310
    PEVT_MU_MSG_INJ,                           //311
    PEVT_MU_FIFO_PKT_RCV,                      //312
    PEVT_MU_RGET_PKT_RCV,                      //313
    PEVT_MU_PUT_PKT_RCV,                       //314
    PEVT_MU_PORT0_16B_WRT,                     //315
    PEVT_MU_PORT0_32B_RD,                      //316
    PEVT_MU_PORT0_64B_RD,                      //317
    PEVT_MU_PORT0_128B_RD,                     //318
    PEVT_MU_PORT1_16B_WRT,                     //319
    PEVT_MU_PORT1_32B_RD,                      //320
    PEVT_MU_PORT1_64B_RD,                      //321
    PEVT_MU_PORT1_128B_RD,                     //322
    PEVT_MU_PORT2_16B_WRT,                     //323
    PEVT_MU_PORT2_32B_RD,                      //324
    PEVT_MU_PORT2_64B_RD,                      //325
    PEVT_MU_PORT2_128B_RD,                     //326
    PEVT_MU_SLV_PORT_RD,                       //327
    PEVT_MU_SLV_PORT_WRT,                      //328
    PEVT_MU_PORT0_PEND_WRT,                    //329
    PEVT_MU_PORT0_PEND_RD,                     //330
    PEVT_MU_PORT1_PEND_WRT,                    //331
    PEVT_MU_PORT1_PEND_RD,                     //332
    PEVT_MU_PORT2_PEND_WRT,                    //333
    PEVT_MU_PORT2_PEND_RD,                     //334
    PEVT_PCIE_INB_RD_BYTES,                    //335
    PEVT_PCIE_INB_RDS,                         //336
    PEVT_PCIE_INB_RD_CMPLT,                    //337
    PEVT_PCIE_OUTB_WRT_BYTES,                  //338
    PEVT_PCIE_OUTB_CFG_X,                      //339
    PEVT_PCIE_OUTB_IO_X,                       //340
    PEVT_PCIE_RX_DLLP,                         //341
    PEVT_PCIE_RX_TLP,                          //342
    PEVT_PCIE_RX_TLP_SIZE,                     //343
    PEVT_PCIE_TX_DLLP,                         //344
    PEVT_PCIE_TX_TLP,                          //345
    PEVT_PCIE_TX_TLP_SIZE,                     //346
    PEVT_DB_PCIE_INB_WRT_BYTES,                //347
    PEVT_DB_PCIE_OUTB_RD_BYTES,                //348
    PEVT_DB_PCIE_OUTB_RDS,                     //349
    PEVT_DB_PCIE_OUTB_RD_CMPLT,                //350
    PEVT_DB_BOOT_EDRAM_WRT_BYTES,              //351
    PEVT_DB_BOOT_EDRAM_RD_BYTES,               //352
    PEVT_DB_MSG_SIG_INTS,                      //353
    PEVT_NW_USER_PP_SENT,                      //354
    PEVT_NW_USER_DYN_PP_SENT,                  //355
    PEVT_NW_USER_ESC_PP_SENT,                  //356
    PEVT_NW_USER_PRI_PP_SENT,                  //357
    PEVT_NW_SYS_PP_SENT,                       //358
    PEVT_NW_USER_WORLD_COL_SENT,               //359
    PEVT_NW_USER_SUBC_COL_SENT,                //360
    PEVT_NW_SYS_COL_SENT,                      //361
    PEVT_NW_COMMWORLD_COL_SENT,                //362
    PEVT_NW_USER_PP_RECV,                      //363
    PEVT_NW_USER_DYN_PP_RECV,                  //364
    PEVT_NW_USER_ESC_PP_RECV,                  //365
    PEVT_NW_USER_PRI_PP_RECV,                  //366
    PEVT_NW_SYS_PP_RECV,                       //367
    PEVT_NW_USER_WORLD_COL_RECV,               //368
    PEVT_NW_USER_SUBC_COL_RECV,                //369
    PEVT_NW_SYS_COL_RECV,                      //370
    PEVT_NW_COMMWORLD_COL_RECV,                //371
    PEVT_NW_USER_PP_RECV_FIFO,                 //372
    PEVT_NW_USER_DYN_PP_RECV_FIFO,             //373
    PEVT_NW_USER_ESC_PP_RECV_FIFO,             //374
    PEVT_NW_USER_PRI_PP_RECV_FIFO,             //375
    PEVT_NW_SYS_PP_RECV_FIFO,                  //376
    PEVT_NW_USER_WORLD_COL_RECV_FIFO,          //377
    PEVT_NW_USER_SUBC_COL_RECV_FIFO,           //378
    PEVT_NW_SYS_COL_RECV_FIFO,                 //379
    PEVT_NW_COMMWORLD_COL_RECV_FIFO,           //380
    PEVT_NW_SENT,                              //381
    PEVT_NW_RECV,                              //382
    PEVT_NW_RECV_FIFO,                         //383
    PEVT_NW_CYCLES,                            //384
    PEVT_CNKNODE_MUINT,                        //385
    PEVT_CNKNODE_NDINT,                        //386
    PEVT_CNKPROC_RSV,                          //387
    PEVT_CNKHWT_SYSCALL,                       //388
    PEVT_CNKHWT_STANDARD,                      //389
    PEVT_CNKHWT_CRITICAL,                      //390
    PEVT_CNKHWT_DECREMENTER,                   //391
    PEVT_CNKHWT_FIT,                           //392
    PEVT_CNKHWT_WATCHDOG,                      //393
    PEVT_CNKHWT_UDEC,                          //394
    PEVT_CNKHWT_PERFMON,                       //395
    PEVT_CNKHWT_UNKDEBUG,                      //396
    PEVT_CNKHWT_DEBUG,                         //397
    PEVT_CNKHWT_DSI,                           //398
    PEVT_CNKHWT_ISI,                           //399
    PEVT_CNKHWT_ALIGNMENT,                     //400
    PEVT_CNKHWT_PROGRAM,                       //401
    PEVT_CNKHWT_FPU,                           //402
    PEVT_CNKHWT_APU,                           //403
    PEVT_CNKHWT_DTLB,                          //404
    PEVT_CNKHWT_ITLB,                          //405
    PEVT_CNKHWT_VECTOR,                        //406
    PEVT_CNKHWT_UNDEF,                         //407
    PEVT_CNKHWT_PDBI,                          //408
    PEVT_CNKHWT_PDBCI,                         //409
    PEVT_CNKHWT_GDBI,                          //410
    PEVT_CNKHWT_GDBCI,                         //411
    PEVT_CNKHWT_EHVSC,                         //412
    PEVT_CNKHWT_EHVPRIV,                       //413
    PEVT_CNKHWT_LRATE,                         //414
  };
